
runtime: nodejs20

env_variables:
  NODE_ENV: "production"
  CLOUD_SQL_CONNECTION_NAME: "your-project:region:instance"
  CLOUD_SQL_USER: "root"
  CLOUD_SQL_DATABASE: "park_finder"
  JWT_SECRET: "your-jwt-secret"
  BASE_URL: "https://your-app-url.app"

instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

handlers:
  - url: /public/uploads/(.*)
    static_files: public/uploads/\1
    upload: public/uploads/(.*)

  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto